Adding a filter for the path column in the dependencies view
pimcore/admin-ui-classic-bundle pull request #225
Opened 2023-08-21 13:31 UTC by Geni2

I introduced the changes almost 6 months ago for adding a filter into the dependencies view for the path column and now I'm facing some issues there because the AdminBundle was deprecated from the Pimcore project I'm doing the relevant changes here according to the documentation and the other changes will be in my Pull Request that is open in Pimcore which I will edit and remove `dependencies.js` and `ElementController.php` file from there.

Here is the link to my other Pull Request: https://github.com/pimcore/pimcore/pull/14671

2023-08-21 13:39 UTC, Geni2 commented
I have read the CLA Document and I hereby sign the CLA

2023-08-21 13:51 UTC, Geni2 commented
I have read the CLA Document and I hereby sign the CLA

2023-08-21 17:24 UTC, Geni2 commented
rechek

2023-08-21 17:25 UTC, Geni2 commented
recheck

2023-08-22 06:40 UTC, dvesh3 commented
@Geni2 please see the tests are failing, which seems related to the changes in the PR. thanks!

2023-08-22 07:22 UTC, Geni2 commented
> @Geni2 please see the tests are failing, which seems related to the changes in the PR. thanks!

@dvesh3 I'm working to fix those failing tests asap. Thank you

2023-09-11 14:32 UTC, robertSt7 requested changes

2023-09-11 14:32 UTC, robertSt7 commented on public/js/pimcore/element/dependencies.js
> +        var plugins = ['pimcore.gridfilters'];
```suggestion
        const plugins = ['pimcore.gridfilters'];
```

2023-09-11 14:32 UTC, robertSt7 commented on public/js/pimcore/element/dependencies.js
> +        var plugins = ['pimcore.gridfilters'];
```suggestion
        const plugins = ['pimcore.gridfilters'];
```

2023-09-19 13:55 UTC, robertSt7 commented
@Geni2 Any news on this?

2023-09-22 11:38 UTC, robertSt7 commented
@Geni2 Please merge 1.x into your branch. Thanks

2023-09-25 13:57 UTC, Geni2 commented
> @Geni2 Any news on this?

Working on this and I hope soon will be some updates here

2023-09-26 11:35 UTC, Geni2 commented
@robertSt7 With the commit that I just made I have included also your requested changes but I did it in a different way. Thank you

2023-09-29 07:58 UTC, merged

2023-09-29 07:58 UTC, robertSt7 commented
@Geni2 Thanks for your effort