add default value and default value generator input fields
pimcore/admin-ui-classic-bundle pull request #252
Opened 2023-08-31 20:38 UTC by jan888adams

Add input fields for default value and default value generator. 

I already have an [MR](https://github.com/pimcore/pimcore/pull/15871) open for the backend part.

2023-10-31 00:02 UTC, jdreesen commented on public/js/pimcore/object/classes/data/multiselect.js
> +                console.log(rec.get("value"));
Leftover debug statement
```suggestion
```

2023-11-07 11:53 UTC, robertSt7 commented
Hi @jan888adams could you please use `let` and `const` instead of `var` for variables in JavaScript? Thanks

2024-04-19 10:58 UTC, robertSt7 commented
Hi @jan888adams I get the following errors, when I start pimcore and try to open a class which contains a Select and Multiselect field. 
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/104770750/2e63aee4-81b7-484c-b625-fe17e4786bc1)
Could you please take a look at this? Thx :)

2024-08-29 07:16 UTC, mattamon commented
> Hi @jan888adams I get the following errors, when I start pimcore and try to open a class which contains a Select and Multiselect field. ![image](https://private-user-images.githubusercontent.com/104770750/323932028-2e63aee4-81b7-484c-b625-fe17e4786bc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTYwNTIsIm5iZiI6MTcyNDkxNTc1MiwicGF0aCI6Ii8xMDQ3NzA3NTAvMzIzOTMyMDI4LTJlNjNhZWU0LTgxYjctNDg0Yy1iNjI1LWZlMTdlNDc4NmJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNzE1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjA0ZWVkNGRlODA5ODRlNDYxOWJmYzM2OWJjMGFiY2I5OGUxYTY4ZWQxZmQ4ZTYwM2IzZWU2ZThmZjY5ZjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iyC5c1ZkJ1CZUf-ltvEKgK7zIsNzbcolRcYcurMUHV4) Could you please take a look at this? Thx :)

I merged the latest 1.x changes into the branch and fixed the class.js error.
Should be good to go now for another review.

2024-09-09 08:12 UTC, mattamon commented
@jan888adams can you please recheck this PR. When I add a new multiselect to a class I get the following error:
![image](https://github.com/user-attachments/assets/36a3fce7-1a9f-4260-bdcf-528e3342037b)

2025-06-04 13:10 UTC, kingjia90 requested changes, later dismissed
Thank you for your PR and patience, finally getting close to merge this 😏 

Just  found some minor inputs to be addressed first, other than needing to be rebased and fix the conflict

2025-06-04 13:10 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +                xtype: "textfield",
```suggestion
                xtype: "hidden",
```
to avoid to show 
![image](https://github.com/user-attachments/assets/196aa848-3c2f-43dc-bdc7-d2ef204c28ec)

2025-06-04 13:10 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> -    }
need to revert this and rename to  `showgrideditor` from `showoptioneditor`, otherwise i get 
![image](https://github.com/user-attachments/assets/7315aa8d-d7ad-424d-b9ff-e3ca6ec34736)
from https://github.com/pimcore/admin-ui-classic-bundle/pull/252/files#diff-3cabd22d0fd1dda6a0151f733e10f8b4472af24bb72e5c8b8d67dc55a6284335R433-R436

as [pointed out](https://github.com/pimcore/admin-ui-classic-bundle/pull/252#issuecomment-2337428052) by my former coworker

2025-06-04 13:10 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> -        editor.edit();
might need some tweak because we only have one column in `Default Value`
![image](https://github.com/user-attachments/assets/10b3ad1c-630c-48a0-a935-f332eec8de56)
opposed to `Selection Options`
![image](https://github.com/user-attachments/assets/73735669-2335-44d7-9cd7-50425d4fa096) and the values are all starting with an `,something`

2025-06-04 13:10 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> -    }
or keep it deleted and remove 
https://github.com/pimcore/admin-ui-classic-bundle/pull/252/files#diff-3cabd22d0fd1dda6a0151f733e10f8b4472af24bb72e5c8b8d67dc55a6284335R433-R435
it we don't want to see the comma separated list with `,something` like the other comment

2025-06-04 13:15 UTC, kingjia90 commented
An entry about the improvement on https://github.com/pimcore/admin-ui-classic-bundle/blob/2.x/CHANGELOG.md would be also highly appreciated

2025-06-04 13:23 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +            fields: ["value"],
wouldn't be better to be an extra column with a checkbox for every options (`field` in `optionsStore`) to avoid setting up default value that do not match any of the options, instead of own grid?

2025-06-04 13:31 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +                value: datax.maxItems,
this can be bypassed by the default value section, so if the limit is 2 and the default are more than 2, eg.4, it would pre-select 4.

2025-06-04 13:33 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +                value: datax.maxItems,
[Screencast from 2025-06-04 15-33-07.webm](https://github.com/user-attachments/assets/134d32cc-9126-4d05-83bc-558e9674f5bd)

If one then select something, it ends up stuck in a forever loop, popup reappears even by pressing `Ok` on the alert

2025-06-04 13:36 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +            fields: ["value"],
ah nevermind, i see why, it wouldn't work with the other dynamic Options Source type, like Options provider.

2025-06-04 13:49 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +                fieldLabel: t("options_provider_class"),
it seems not working with the other dynamic option provider, can you also check on this?

2025-06-11 08:26 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> -        editor.edit();
resolved  by https://github.com/pimcore/admin-ui-classic-bundle/pull/252/commits/eba95803ddbbe5f8dcd9476f1393a891dd8009c5#diff-3cabd22d0fd1dda6a0151f733e10f8b4472af24bb72e5c8b8d67dc55a6284335R521

2025-06-11 08:36 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +                value: datax.maxItems,
resolved by https://github.com/pimcore/admin-ui-classic-bundle/pull/252/commits/1433649aeaeeaf837c8cd3975bc68d20fc1861eb

2025-06-11 08:53 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +                fieldLabel: t("options_provider_class"),
disabling for these type, it's not supported, resolved  by https://github.com/pimcore/admin-ui-classic-bundle/pull/252/commits/c7136ab958127f2a25dfd46dd7b7fc68145f31e5

2025-06-11 10:12 UTC, kingjia90 commented on public/js/pimcore/object/classes/data/multiselect.js
> +                    if (count >= this.datax.maxItems){
```suggestion
                    if (this.datax.maxItems > 0 && count >= this.datax.maxItems){
```
otherwise it would be always reaching the limit

2025-06-11 10:44 UTC, robertSt7 approved these changes

2025-06-11 10:52 UTC, merged