Use Maintenance Mode Helper
pimcore/admin-ui-classic-bundle pull request #274
Opened 2023-09-15 11:21 UTC by dvesh3

Related to https://github.com/pimcore/pimcore/pull/15954

2023-09-19 16:44 UTC, kingjia90 commented on src/Controller/Admin/MiscController.php
> +            $maintenanceModeHelper->deactivate();
```suggestion
            if (Tool\Admin::isInMaintenanceMode()){
               Tool\Admin::deactivateMaintenanceMode();
            }
            $maintenanceModeHelper->deactivate();
```
more edge case but without this, if  you were already in legacy maintenance mode, you would see the icon but it won't exit by clicking it
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/6014195/48cb51dc-248e-45fe-bef7-4d38f5e5dae0)
and would break script that may be calling `pimcore.helpers.deactivateMaintenance`.

2023-09-19 17:02 UTC, kingjia90 requested changes
LGTM just one particular case that could be covered by deactivating both approaches

2023-09-20 09:47 UTC, dvesh3 commented on src/Controller/Admin/MiscController.php
> +            $maintenanceModeHelper->deactivate();
Good catch! yes, we need to check if the maintenance file exists first.

2023-09-21 08:57 UTC, kingjia90 approved these changes

2023-09-22 10:49 UTC, dvesh3 commented
> LGTM just one particular case that could be covered by deactivating both approaches, until we remove the support for legacy mode and there is missing a followup for this
> 
> https://github.com/pimcore/admin-ui-classic-bundle/blob/82aa7a8e6e5a8157c8ff96e027be3a75a9bfd9d2/src/Security/Authenticator/AdminAbstractAuthenticator.php#L106-L109

This is deprecated and will be removed in Pimcore 12. please see https://github.com/pimcore/pimcore/pull/15991

2023-09-22 12:09 UTC, merged