Bugfix - Sharing grids to users
pimcore/admin-ui-classic-bundle pull request #654
Opened 2024-08-07 19:02 UTC by torqdev

Bugfix for sharing grid configs to other users.

Can be replicated on `demo.pimcore.fun`. Steps to recreate:
1. Create grid config, and navigate to 'Save & Share'.
2. Add users. Do not set 'Share globally'.
3. Save & Share

2024-08-09 06:52 UTC, martineiber requested changes
Thank you for this fix. LGTM :+1: 

I have one more Request. Could you also change this for the AssetGrid here?
https://github.com/pimcore/admin-ui-classic-bundle/blob/7554a0fc3fd89d69e6c90fadf62d3f3edaa03d56/src/Controller/Admin/Asset/AssetHelperController.php#L649

2024-08-09 06:58 UTC, blankse commented
I think we could change the line 978 to:
` $sharedUsers = array_map('intval', explode(',', $sharedUserIds));`

So we can remove lot of (int) casts.

Right?

2024-08-09 07:08 UTC, martineiber commented
> I think we could change the line 978 to: ` $sharedUsers = array_map('intval', explode(',', $sharedUserIds));`
> 
> So we can remove lot of (int) casts.
> 
> Right?

This would also be a nice solution :)

2024-08-21 15:36 UTC, blankse commented on src/Controller/Admin/Asset/AssetHelperController.php
> +                    if ((int) $favouriteGridConfig->getOwnerId() === $id) {
getOwnerId() can only be int or null. So there is also no convert needed.
```suggestion
                    if ($favouriteGridConfig->getOwnerId() === $id) {
```

2024-08-21 15:36 UTC, blankse commented on src/Controller/Admin/DataObject/DataObjectHelperController.php
> +                    if ((int) $favouriteGridConfig->getOwnerId() === $id) {
```suggestion
                    if ($favouriteGridConfig->getOwnerId() === $id) {
```

2024-08-23 07:33 UTC, martineiber approved these changes
LGTM :+1: 
Thank you for your contribution

2024-08-23 07:33 UTC, merged