Fixes cell width not taking all space
pimcore/admin-ui-classic-bundle pull request #694
Opened 2024-09-17 13:36 UTC by mhgtlc

Fixes https://github.com/pimcore/admin-ui-classic-bundle/issues/688

2024-09-20 09:46 UTC, robertSt7 commented
@mhgtlc Thanks for coming up with a solution. But I think when we remove this code then we will have this problem again, right? 
https://github.com/pimcore/admin-ui-classic-bundle/pull/566

2024-09-20 10:13 UTC, mhgtlc commented
> @mhgtlc Thanks for coming up with a solution. But I think when we remove this code then we will have this problem again, right? #566

@robertSt7 probably yes, in this case we need another solution I guess

2025-08-19 08:33 UTC, kingjia90 requested changes

2025-08-19 08:33 UTC, kingjia90 commented on public/js/pimcore/object/tags/table.js
> +                forceFit: true
```suggestion
                forceFit: true,
                listeners: {
                    refresh: function (dataview) {
                        Ext.suspendLayouts();
                        let totalWidth = 0;
                        const columns = dataview.panel.columns;
                        
                        Ext.each(columns, function (column) {
                            totalWidth += column.getWidth();
                        });
                        
                        if (totalWidth > this.fieldConfig.width){
                            Ext.each(columns, function (column) {
                                column.autoSize();
                            });
                        }

                        Ext.resumeLayouts(true);
                    }.bind(this)
                }
```
This would be the best of the 2 world, so when the column

2025-08-19 08:33 UTC, kingjia90 commented on public/js/pimcore/object/tags/table.js
> +                forceFit: true
Without listener (as the change in this PR)
<img width="578" height="307" alt="image" src="https://github.com/user-attachments/assets/1dcf6170-f285-4f84-9d96-507d0bb3e311" />

With listener (https://github.com/pimcore/admin-ui-classic-bundle/pull/566)
<img width="578" height="307" alt="image" src="https://github.com/user-attachments/assets/f8c988c1-2b6b-4e0d-90eb-93e35040235a" />


with the suggestion above
<img width="578" height="307" alt="image" src="https://github.com/user-attachments/assets/89e8895f-513f-4802-b607-1dd4b79b10bb" />

2025-08-19 10:29 UTC, merged